apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-da
  labels:
    app: trust-da
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-da
  template:
    metadata:
      labels:
        app: trust-da
    spec:
      containers:
      - name: trust-da
        image: trust-da:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: "5120Mi"
            cpu: "500m"
        env:
        - name: MONITORING_ENABLED
          value: "false"
        - name: TRUSTIFY_HOST
          value: http://trustify:8080/api/v2/
        - name: TRUSTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: trust-da-secret
              key: trustify.client.id
        - name: TRUSTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: trust-da-secret
              key: trustify.client.secret
        - name: TRUSTIFY_AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: trust-da-secret
              key: trustify.auth.server.url
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 9000
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 9000
          initialDelaySeconds: 2
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: trust-da
  labels:
    app: trust-da
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: trust-da
